[tool.poetry]
name = "homework-19-2"
version = "0.1.0"
description = ""
authors = ["Alexander Polikarpov <alex-polikarpov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
